config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users
  resources :discussions do
    resources :likes
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  has_many :taggings
  has_many :tags, through: :taggings

  has_rich_text :content
  belongs_to :user
  has_one_attached :ref_photo

  has_many :likes, dependent: :destroy

  # code for adding taggings section
    def all_tags=(names)
      self.tags = names.split(',').map do |name|
        Tag.where(name: name.strip).create!
      end
    end

    def all_tags
      tags.map(&:name).join(', ')
    end

  # for searching
  def self.tagged_with(name)
    Tag.find_by_name!(name).discussions
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :discussion
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :discussion
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #
  # has_many :taggings
  # has_many :tags, through: :taggings

  has_many :likes, dependent: :destroy

  validates :username, presence: :true, uniqueness: { case_sensitive: false }
  validates :email, presence: :true, uniqueness: { case_sensitive: false }
  before_save {self.email = email.downcase}
  before_save {self.username = username.downcase}
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,authentication_keys: [:login]

    validate :validate_username

    def validate_username
    if User.where(email: username).exists?
    errors.add(:username, :invalid)
    end
    end

has_many :discussions, dependent: :destroy

  attr_writer :login

  def login
    @login || self.username || self.email
  end

     def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end
    end





end #main end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :set_discussion, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index]
  before_action :check_discussion_own_same_user, only: [:edit, :destroy, :update]

  # GET /discussions
  # GET /discussions.json
  def index
    if user_signed_in?
    @discussions = current_user.discussions.order("created_at DESC")
    else
      @discussions = Discussion.all.order("created_at DESC")
    end
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
  end

  # GET /discussions/new
  def new
    @discussion = Discussion.new
  end

  # GET /discussions/1/edit
  def edit
    @discussion = Discussion.find(params[:id])
    unless current_user.id == @discussion.user_id
      redirect_to @discussion
      flash[:notice] = "you shall n't do that !..."
    end
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = current_user.discussions.build(discussion_params)
    @discussion.user_id = current_user.id
    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: 'Discussion was successfully created.' }
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1
  # PATCH/PUT /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to @discussion, notice: 'Discussion was successfully updated.' }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to discussions_url, notice: 'Discussion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discussion
      @discussion = Discussion.find(params[:id])
    end

    def check_discussion_own_same_user
      if @discussion.user_id = current_user.id
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discussion_params
      params.require(:discussion).permit(:title,:content, :ref_photo, :all_tags)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # if user_signed_in?
    #   @discussions = Discussion.where('user_id =?', current_user.id)
    # else
    #   @discussions = Discussion.all.order("created_at DESC")
    # end

    if params[:tag]
      @discussions = Discussion.tagged_with(params[:tag])
    else
      @discussions = Discussion.all.order("created_at DESC")
    end #end of if
  end # method index end

end # end of class

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post

  def create
    unless already_liked?
      @discussion.likes.create(user_id: current_user.id)
    else
      flash[:notice] = "You cannot do more than once."
    end
    redirect_to @discussion
  end

  private

  def already_liked?
    @discussion.likes.where(user_id: current_user.id, discussion_id: params[:discussion_id]).exists?
  end

  def find_post
    @discussion = Discussion.find(params[:discussion_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date(date)
    date.strftime("%b%d%Y, %I")
  end

  def format_date_discussion(date)
    date.strftime("%B %d, %Y")
  end

# 50150083276269
  def gravatar_for(email)
    gravatar_id = Digest::MD5::hexdigest(email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag gravatar_url, alt: email, class: "rounded-full"
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize: local_assigns[:in_gallery] ? "800x600" : "1024x768" ) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/discussions/_form.html.erb
<%= simple_form_for(@discussion) do |f| %>
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="form-inputs">
  <%= f.input :title %>
</div>

<div class="form-inputs">
  <%= f.rich_text_area :content, input_html: {class: "textarea is-warning"}, wrapper: false, label_html: { class: "label"} %>
</div>

<div class="form-inputs text input text-indigo-darker mt-6">
    <%= f.label :all_tags %>
    <%= f.text_field :all_tags, placeholder: "Tags separated with comma", class: "text-indigo-darker ml-6" %>
</div>

<div class="form-inputs">
  <%= f.label :ref_photo %>
  <%= f.file_field :ref_photo %>
</div>

<div class="form-actions mt-3">
  <%= f.button :submit, class: "button is-danger mt-5" %>
</div>
<% end %>

<script>

document.addEventListener('turbolinks:load', () => {
  //console.log("yoyo");
  $('#discussion_content').froalaEditor();
});
</script>

app/views/discussions/edit.html.erb
<h1>Editing Discussion</h1>

<%= render 'form', discussion: @discussion %>

<%= link_to 'Show', @discussion %> |
<%= link_to 'Back', discussions_path %>

app/views/discussions/index.html.erb
<% if user_signed_in? %>
  <p id="notice"><%= notice %></p>

<h1>Discussions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discussions.each do |discussion| %>
      <tr>
        <td><%= discussion.title %></td>
        <td><%= discussion.content %></td>

        <td><%= link_to 'Show', discussion %></td>
        <td><%= link_to 'Edit', edit_discussion_path(discussion) %></td>
        <td><%= link_to 'Destroy', discussion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discussion', new_discussion_path, {:class => "button is-primary btn rounded border-b-4 border-b-red-light "} %>

<% end %>

app/views/discussions/new.html.erb
<h1>New Discussion</h1>

<%= render 'form', discussion: @discussion %>

<%= link_to 'Back', discussions_path %>

app/views/discussions/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container bg-white">
<div class="article is-centered ">
  <p>
    <strong>Title:</strong>
    <%= @discussion.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= @discussion.content %>
  </p>

  <% check_ref_photo = @discussion.ref_photo %>
  <% if check_ref_photo.present?  %>
    <%= image_tag @discussion.ref_photo %>
  <% else %>
    <div class="tag is-primary p6">
      <h2 class="subtitle is-3">Photo Needed !!</h2>
    </div>
  <% end %>

  <div class="bg-indigo--dark">
    <h3 class="leading-tight ">
      <b>Related Tags: </b>  <%= @discussion.all_tags %>
    </h3>
  </div>


</div>

</div>

<br>
<br>
<%= link_to "👏", discussion_likes_path(@discussion), method: :post %>
<p class="text-2xl text-black"><%= @discussion.likes.count %><%= @discussion.likes.count == 1 ? " Like" : " Likes" %> </p>
<br>
<br>
<%= link_to 'Edit', edit_discussion_path(@discussion) %> |
<%= link_to 'Back', discussions_path %>


<!--Comments section-->
<article class="uk-comment bg-white">
    <header class="uk-comment-header uk-grid-medium uk-flex-middle" uk-grid>
        <div class="uk-width-auto">
          <div class="uk-comment-avatar">
             <%= gravatar_for @discussion.user.email %>
          </div>
        </div>
        <div class="uk-width-expand">
            <h4 class="uk-comment-title uk-margin-remove"><a class="uk-link-reset" href="#">Author</a></h4>
            <ul class="uk-comment-meta uk-subnav uk-subnav-divider uk-margin-remove-top">
                <li><a href="#">12 days ago</a></li>
                <li><a href="#">Reply</a></li>
            </ul>
        </div>
    </header>
    <div class="uk-comment-body">
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
    </div>
</article>


<!--test ing  ui-->

app/views/home/_dashboard.html.erb
<section class="mb-10">
  <div class="container is-centered rounded shadow">
    <br>
    <h3 class="title leading-tight is-4 has-text-centered text-indigo-darker text-xl">Welcome <%= current_user.username %> 👏</h3>
    <h3 class="subtitle leading-tight is-6 has-text-centered mt-5 py-3 text-indigo-dark text-sm">Its a new modern UI designed discussion webapp in one platform for
      Developers and as well as Designers. We made abstract your commiunity workspace more bigger and more organize.
      Spread Love 🎈 <br> <br></h3>
  </div>
</section>


</div>

<section>

<!--testing ui-->

<!-- <div class="uk-card uk-card-default uk-width-1-2@m">
    <div class="uk-card-header">
      <div class="uk-grid-small uk-flex-middle" uk-grid>
        <div class="uk-width-auto">

        </div>
        <div class="uk-width-expand">
          <h3 class="uk-card-title uk-margin-remove-bottom">Title</h3>
          <p class="uk-text-meta uk-margin-remove-top"><time datetime="2016-04-01T19:00">April 01, 2016</time></p>
        </div>
      </div>
    </div>
    <div class="uk-card-body">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
    </div>
    <div class="uk-card-footer">
      <a href="#" class="uk-button uk-button-text">Read more</a>
    </div>
  </div> -->
<!---->

  <div class="container is-centered rounded bg-white shadow-lg border-b-4 border-bg-grey-lighter mb-6">
    <% @discussions.each do |discussions| %>
      <div class="bg-indigo-lighter mb-0">
        <h3 class="clearfix leading-loose text-5xl ml-6 text-black link"><%= link_to discussions do %>
          <%= discussions.title %>
          <% end %>
          </h3>
      </div>
      <div class="mb-6">
        <div class="clearfix flex inline-flex justify-center align-items"><%= gravatar_for discussions.user.email %></div>
        <div class="flex flex-wrap inline-flex pin pin-r mr-4 bg-yellow mb-3 px-6 rounded">
          <p class="font-bold text-black flex-wrap">
            <%= link_to @user do  %>
            <%= discussions.user.username %>
              <% end  %>
            . updated_at: <%= format_date_discussion(discussions.updated_at) %> </p>
        </div>
        <br>
        <div class="ml-12 text-indigo-darker "> <%= discussions.all_tags %> </div>
      </div>

      <div class="flex justify-between">
        <div class="text-grey-darker inline-flex flex-b bg-indigo-dark text-white rounded text-center border border-black px-4 py-2 m-2"> 👏🏻
          <p class=""><%= discussions.likes.count %><%= discussions.likes.count == 1 ? " Like" : " Likes" %> </p>
        </div>
        <div class="text-grey-darker inline-flex flex-b rounded text-center border border-black px-4 py-2 m-2"> 💬 22</div>
        <div class="text-grey-darker inline-flex bg-red text-white flex-b rounded flex-wrap justify-end text-center border border-black px-4 py-2 m-2">😓 12</div>
      </div>
    <% end %>
    <!-- START ARTICLE -->
<!--    <div class="card article shadow-lg rounded p-2">-->
<!--      <div class="card-content">-->
<!--        <div class="media">-->
<!--          <div class="media-center is-rounded ">-->
            <%#= image_tag "rails.png", alt: "placeholder image", class: "rounded" %>
<!--          </div>-->
<!--          <div class="media-content has-text-centered">-->
<!--            <p class="title article-title">Sapien eget mi proin sed 🔱</p>-->
<!--            <p class="subtitle is-6 article-subtitle">-->
<!--              <a href="#">@<%#= current_user.username %> </a> on February 17, 2018-->
<!--            </p>-->
<!--          </div>-->
<!--        </div>-->
<!--        <div class="content article-body">-->
<!--          <p>-->
<!--            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Accumsan lacus vel facilisis volutpat est velit egestas. Sapien eget mi proin sed. Sit amet mattis vulputate enim.-->
<!--          </p>-->
<!--          <p>-->
<!--            Commodo ullamcorper a lacus vestibulum sed arcu. Fermentum leo vel orci porta non. Proin fermentum leo vel orci porta non pulvinar. Imperdiet proin fermentum leo vel. Tortor posuere ac ut consequat semper viverra. Vestibulum lectus mauris ultrices eros.-->
<!--          </p>-->
<!--          <h3 class="has-text-centered">Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Cras tincidunt lobortis feugiat vivamus.</h3>-->
<!--          <p>-->
<!--            In eu mi bibendum neque egestas congue quisque egestas diam. Enim nec dui nunc mattis enim ut tellus. Ut morbi tincidunt augue interdum velit euismod in. At in tellus integer feugiat scelerisque varius morbi enim nunc. Vitae suscipit tellus mauris a diam.-->
<!--            Arcu non sodales neque sodales ut etiam sit amet.-->
<!--          </p>-->
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
  </div>
</section>
<br>

app/views/home/_home.html.erb
<%# <% <section class="hero is-danger">
	<div class="hero-body">
		<div class="container has-text-centered">
			<h1 class="title">
				Welcome to Projekt
			</h1>
			<h2 class="subtitle">
				A small project management app built with Ruby on Rails
			</h2>
		</div>
	</div>
</section> %> %>
<!--section class="section">
	<div class="container">
		<div class="columns">
			<div class="column is-7">
				<div class="content">
					<h3 class="title is-3">Why is discussions so awesome?</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum quo voluptatibus blanditiis quis odit rerum error laudantium quidem, est tenetur dolorum mollitia, molestiae quibusdam ipsam vero autem modi et nobis.</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur, dignissimos nihil, impedit distinctio perspiciatis, soluta repellat expedita libero vitae ea debitis quae excepturi aperiam dolorem veritatis possimus, quos molestias molestiae.</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A quaerat, tempore qui! Veniam sequi adipisci aliquam rerum, quas laborum expedita, illum repellendus sunt sit necessitatibus minus quo assumenda provident numquam.</p>
				</div>
			</div>
			<div class="column is-4 is-offset-1">
				<h4 class="subtitle is-4">Sign Up Today</h4>
				<%= link_to 'Sign Up', new_user_registration_path, class: 'button is-link is-outlined' %>
			</div>
		</div>
	</div>
</section-->

<div class="container">
        <!-- START ARTICLE FEED -->
        <section class="articles">
            <div class="column is-8 is-offset-2">
                <!-- START ARTICLE -->
                <div class="card article rounded box-shadow">
                    <div class="card-content">
                        <div class="media">
                            <div class="media-content has-text-centered">
                                <p class="title article-title">Introducing a new feature for paid subscribers</p>
                                <div class="tags has-addons level-item">
                                    <span class="tag is-rounded is-danger">@sounish003</span>
                                    <span class="tag is-rounded">Feb 17, 2019</span>
                                </div>
                            </div>
                        </div>
                        <div class="content article-body">
                            <p>Non arcu risus quis varius quam quisque. Dictum varius duis at consectetur lorem. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. </p>
                            <p>Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Accumsan lacus vel facilisis volutpat. Non sodales neque sodales ut etiam.
                                Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus.</p>
                            <h3 class="has-text-centered">How to properly center tags in bulma?</h3>
                            <p> Proper centering of tags in bulma is done with class: <pre>level565-item</pre>
                                Voluptat ut farmacium tellus in metus vulputate. Feugiat in fermentum posuere urna nec. Pharetra convallis posuere morbi leo urna molestie.
                                Accumsan lacus vel facilisis volutpat est velit egestas. Fermentum leo vel orci porta. Faucibus interdum posuere lorem ipsum.</p>
                        </div>
                    </div>
                </div> <br>
<!-- END ARTICLE -->

app/views/home/index.html.erb
<% unless user_signed_in? %>
  <div>
    <%= render 'home' %>
  </div>

  <div class="flex flex-wrap items-center justify-center mt-10 ">
  <%= link_to "Log In", new_user_session_path, {:class => "button font-bold btn mr-10 is-danger shadow-lg p-5 text-centered"} %>

  <%= link_to "Sign Up", new_user_registration_path, {:class => "button btn bg-blue text-white font-bold leading-tight shadow-lg p-5 text-centered"} %>

  </div>

  <% else %>
   <%= render 'dashboard' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>🤨😜 Discussions </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_tag 'application','data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <%# <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"> %>
      <!--material icons-->
       <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--getin uikit-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/2.xx.x/css/uikit.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/2.xx.x/js/uikit.min.js"></script>
  </head>

  <body>

  <!--Nav bar start-->
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="container">
            <div class="navbar-brand">

            <%= link_to root_path do %>
                    <div class="navbar-item">
                      <h2 class="subtitle is-5 has-text-bold" style="font-family: monospace;">Discussions</h2>
                    </div>
            <% end %>

                <a class="navbar-burger burger"  aria-label="menu" aria-expanded="false" data-target="navbarMenu">
                <span></span>
                <span></span>
                <span></span>
                </a>
            </div>
            <div id="navbarMenu" class="navbar-menu">
                <div class="navbar-end">
<!--                    <a class="navbar-item is-active">-->
<!--                            Discussions-->
<!--                        </a>-->
                <%= link_to "My Discussions", discussions_path,  class: "navbar-item link text-black" if (user_signed_in?) %>
            <a class="navbar-item">
                <form class="shadow flex" action="/discussions" method="get" accept-charset="UTF-8">
                  <input type="text" name="tag" id="tag" placeholder="search" class="w-full rounded bg-white p-2">
                    <button type="submit" class="bg-white w-auto flex justify-end items-center text-indigo-darker p-2 hover:text-indigo-dark">
                      <i class="material-icons text-xl">search</i>
                    </button>
                </form>
            </a>
                    <a class="navbar-item">
                            Team
                        </a>
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">
                                Account
                            </a>
                        <% unless user_signed_in? %>
                            <div class="navbar-dropdown">
                                <a class="navbar-item text-white bg-orange hover:bg-orange-dark" href="/users/sign_in">
                                        Log In
                                    </a>
                                <%# <a class="navbar-item">
                                        Settings
                                    </a> %>
                                        <hr class="navbar-divider">
                                        <div class="navbar-item bg-red text-white hover:bg-red-dark">
                                        <a href="/users/sign_up" class="text-white hover:text-white">Sign Up</a>
                                        </div>
                            <% else %>
                                    <div class="navbar-item bg-red text-white hover:bg-red-dark">
                                    <%= link_to "Log out", destroy_user_session_path, method: :delete, data: {confirm: "Goodbye #{current_user.username} !"}, class: "link text-white" %>
                                    </div>
                                </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <!-- END NAV -->


    <div class="container rounded p-10">
<!--nav bar-->
  <% if !user_signed_in? %>
    <section class="hero rounded is-secondary shadow-lg is-medium is-bold">
        <div class="hero-body">
            <div class="container has-text-centered">
                <h1 class="title">A Blog Purpose Website Build on Vue and Rails. <br></h1>
                <h2 class="subtitle is-4">For Designers and Developers Campire Discussion Forum</h2>
            </div>
        </div>
    </section>

  <% end %>

      <%= yield %>
    </div>

    <!--script for navbar open-->
      <script>
        document.addEventListener('DOMContentLoaded', () => {

      // Get all "navbar-burger" elements
      const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

      // Check if there are any navbar burgers
      if ($navbarBurgers.length > 0) {

        // Add a click event on each of them
        $navbarBurgers.forEach( el => {
          el.addEventListener('click', () => {

            // Get the target from the "data-target" attribute
            const target = el.dataset.target;
            const $target = document.getElementById(target);

            // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
            el.classList.toggle('is-active');
            $target.classList.toggle('is-active');

          });
        });
      }

    });

      </script>

  </body>

</html>